### PR TITLE
[CI] Check links to crates.io, and link fix

### LINKED ISSUE #6175: [infra] Support checking of crates.io URLs
Because of:

- https://github.com/rust-lang/crates.io/issues/788

we can't directly link-check URLs into crates.io, but with our new custom URL validation we might be able to work around the 404 return by crates.io

### PR DESCRIPTION
**Pull request by chalin**
- Fixes #6175
- Contributes to #5017
- Enables the checking of links to crates.io, despite https://github.com/rust-lang/crates.io/issues/788
- Fixes package name

/cc @open-telemetry/rust-approvers

### CODE REVIEW

File: scripts/get-url-status.mjs [hunk 1]
```diff
@@ -32,13 +56,13 @@ async function getUrlHeadless(url) {
     // https://github.com/rust-lang/crates.io/issues/788
     if (url.startsWith(cratesIoURL)) {
       const crateName = url.split('/').pop();
-      // Crate found iff title is `${crateName} - crates.io: Rust Package Registry`
-      if (!title.startsWith(crateName)) status = 404;
+      // E.g. 'https://crates.io/crates/opentelemetry-sdk' -> 'opentelemetry-sdk'
+      const crateNameRegex = new RegExp(crateName.replace(/-/g, '[-_]'));
+      // Crate found iff title starts with createName (in kebab or snake case)
```
Comment (tiffany76) [inline scripts/get-url-status.mjs:61]:
```suggestion
      // Crate found if title starts with createName (in kebab or snake case)
```

**Review by tiffany76 — APPROVED** [review]
RSTLGTM.

**Comment by theletterf** [comment]
Seems like the alert doesn't dismiss itself, @chalin. Shall we mute it manually?

**Comment by chalin** [comment]
I'll tackle it, thanks for point it out.
