### PR TITLE
[CI] Auto-version update fix: match on PR num

### LINKED ISSUE #6271: Auto-update versions script failing
Example:
```
Run ./scripts/auto-update/all-versions.sh
> ./scripts/auto-update/version-in-file.sh opentelemetry-collector-releases
        vers content/en/docs/collector/_index.md
        collector_vers content/en/docs/security/_index.md
HEAD is now at 8fbd3a5 [ja] translate contributing/pull-requests  into ja (#6197)
REPO:            opentelemetry-collector-releases
LATEST VERSION:  cmd/builder/v0.119.0
SEARCHING for:   '^ *vers:' in content/en/docs/collector/_index.md
CURRENT VERSION:   vers: 0.118.0
+ sed -i.bak -e 's/\(^ *vers:\) .*/\1 cmd/builder/v0.119.0/' content/en/docs/collector/_index.md
sed: -e expression #1, char 26: unknown option to `s'
```

https://github.com/open-telemetry/opentelemetry.io/actions/runs/13244142818/job/36966386401

Looks like it started failing on [february 4th](https://github.com/open-telemetry/opentelemetry.io/actions/workflows/auto-update-versions.yml?page=6):

Image

### PR DESCRIPTION
**Pull request by chalin**
- Followup to #6272
- Fixes #6271, for real 🤞 😄

### CODE REVIEW

File: scripts/auto-update/version-in-file.sh [hunk 1]
```diff
@@ -86,13 +86,17 @@ body="Update $repo version to \`$latest_version\`.
 See https://github.com/open-telemetry/$repo/releases/tag/$latest_version."
 branch="opentelemetrybot/auto-update-$repo-$latest_version"
 
+echo "Looking for existing PRs with branch '$branch'."
 existing_pr_all=$(gh pr list --state all --head "$branch")
-existing_pr_count=$(echo "$existing_pr_all" | wc -l)
-if [ "$existing_pr_count" -gt 0 ]; then
+# `gh pr list` a list of PRs, each line starting with a PR number if there's a
```
Comment (tiffany76) [inline scripts/auto-update/version-in-file.sh:91]:
```suggestion
# `gh pr list` is a list of PRs, each line starting with a PR number if there's a
```

**Review by tiffany76 — APPROVED** [review]
